### ISSUE TITLE
altitude_diff missing - enhancment: add decoded value and calculate GNSS Alt

### ISSUE THREAD

**Issue by ghost** [junzis/pyModeS#107]
https://github.com/junzis/pyModeS/blob/83e22892ba80829987acd5d84cb27f90532aef17/pyModeS/decoder/adsb.py#L8

`altitude_diff` missing to provide the GNSS altitude (height above ellipsoid (HAE) WGS84) difference from the barometric altitude "alt" (which is standard pressure, and not even MSL).

Request enhancement to decode this value and present to live-modes streamer and display.
Also request enhancement to automatically calculate the HAE feet (GNSS altitude) from decoded `altitude `(barometric) https://github.com/junzis/pyModeS/blob/83e22892ba80829987acd5d84cb27f90532aef17/pyModeS/decoder/adsb.py#L136
and provide a "calculated" GNSS Altitude in HAE feet or meters.

**Comment by junzis** [comment]
`altitude_diff()` can be found at:
https://github.com/junzis/pyModeS/blob/83e22892ba80829987acd5d84cb27f90532aef17/pyModeS/decoder/bds/bds09.py#L106
