### ISSUE TITLE
BDS09 local variable trk referenced before assignment

### ISSUE THREAD

**Issue by fredclausen** [junzis/pyModeS#109]
https://github.com/junzis/pyModeS/blob/83e22892ba80829987acd5d84cb27f90532aef17/pyModeS/decoder/bds/bds09.py#L69

Message ```8DAE041599080000000000E25EA8``` can cause an issue where the variable trk is referenced before assignment

Traceback

```  File "/Library/Python/3.8/site-packages/pyModeS/decoder/adsb.py", line 167, in velocity
    return airborne_velocity(msg, source)
  File "/Library/Python/3.8/site-packages/pyModeS/decoder/bds/bds09.py", line 69, in airborne_velocity
    trk_or_hdg = round(trk, 2)
UnboundLocalError: local variable 'trk' referenced before assignment```

**Comment by junzis** [comment]
@federicoorta, thanks for reporting the bug! This should be fixed in one of recent updates.
