### ISSUE TITLE
Determine the country of registration for an aircraft

### ISSUE THREAD

**Issue by deepcoder** [junzis/pyModeS#123]
I apologize, I'm sure this is such a basic question. I am not able to see away to determine the country of origin of an aircraft from any of the apis here. Or is this something that is determined directly from the IAOC code of the aircraft. Thx!

**Comment by xoolive** [comment]
Each `icao24` identifier fits within a range that is assigned to a country. There are official lists here and there, e.g. [here](https://github.com/xoolive/traffic/blob/master/traffic/data/basic/patterns.json)

Be aware that in some cases, the country associated with the `icao24` id could differ from the country you can infer from the registration/tail number.

**Comment by deepcoder** [comment]
Thank you for you reply and information. I will try to use this JSON data and see what I get.
