### ISSUE TITLE
hdg values not being dumped

### ISSUE THREAD

**Issue by ElSabio97** [junzis/pyModeS#126]
Hi @junzis !!

Why can't i get the hdg values exported to the csv file using `--dumpto` ? 

We can export these to the csv `gs, trk, roc, roc60baro, roc60ins, tas50, roll50, trk50, gs50, lat, lon, alt, cs, rtrk50` but not `hdg`.

**Comment by junzis** [comment]
Hi @ElSabio97, it is added now in b90932e51d1e6b2639ed822514e1f2888d659064
