### ISSUE TITLE
ModuleNotFoundError: No module named 'pyModeS.decoder.flarm.decode'

### ISSUE THREAD

**Issue by stinerk** [junzis/pyModeS#153]
The above error occurred continuously while linking pyModeS to use Xoolive's Traffic library.
A number of steps were taken to fix this, and eventually "__ini__.py" in the decoder/flarm folder.I modified "from .decode" to "from .." and it was resolved. I don't know if it's just a problem with my computer, but it would be nice if you could check the code.

**Comment by xoolive** [comment]
Hi @stinerk 
The code is correct and continuous integration is working properly.
Would you have a reproducible example?
Otherwise, I would recommend a pip install in a fresh environment.

**Comment by stinerk** [comment]
I think maybe the environment I created may not be common. However, there was no other special setting, and it went through the installation process in the way that the traffic document tells it. However, when I tried to access the historical database, the above error continued to occur, and in the end, the pyModeS library had to solve it, so it was corrected. Since then, the code has been working without any problems. If there is another problem, I will report it again. 
Apart from this, can you tell me if you know how to decode Threat Identity information exactly when processing BDS3,0 messages in ModeS?
This is driving me crazy...
