### ISSUE TITLE
Decoding temperatue in ehs.py

### ISSUE THREAD

**Issue by srofen** [junzis/pyModeS#19]
when I was decoding temperature in df20 and df21 I got wrong results. When I changed function "def temp44(msg, rev=False)", results was OK. see attached file for details.

[weather.txt](https://github.com/junzis/pyModeS/files/1949999/weather.txt)

**Comment by junzis** [comment]
@srofen, thanks for the update. This is now fixed by 11b85b6 in the dev-2.0 branch.
