### ISSUE TITLE
 Whether ADS-B include time information?

### ISSUE THREAD

**Issue by bupt-zsp** [junzis/pyModeS#30]
Dear researcher:
      Thanks for your job first. It's a great job for me to learn about ADS-B. After I read the guide book, I find all the time stamp seems like a local time. So I want to know whether ADS-B broadcast it's own clock in ADS-B frame. If so, how can I capture it.

**Comment by junzis** [comment]
ADS-B does not broadcast any time information. You have to rely on the receiver clock. Some ADS-B receiver can connect to a GPS receiver to provide an accurate timestamp.
