### ISSUE TITLE
Decoding Raw Data Stream

### ISSUE THREAD

**Issue by kelvinxuande** [junzis/pyModeS#40]
Hi,

Thank you for the great job done so far. I am using Radarcape for one of my school projects and am tasked to extract some key information such as the squawk code and timestamp from the data received.

I have wrote afew lines of code: 
[client.txt](https://github.com/junzis/pyModeS/files/3196098/client.txt)
and printed the data acquried onto .txt for reference: 
[sample_output.txt](https://github.com/junzis/pyModeS/files/3196101/sample_output.txt)

However, from the readings of your library and more documentations found online, I am clueless as to what to do next; so as to obtain the information in hexadecimal form (I pressume).
Any tips, or have I done something wrong?

Best regards.

**Comment by junzis** [comment]
The TCP client module from pyModeS can be used here. You need to reimplement the ``handel_messages()`` function from the ``BaseClient`` class to write your own logic to handle the messages. Here is an example:

```
from pyModeS.extra.tcpclient import BaseClient

# define your custom class extending the BaseClient
#   - implement your handle_messages() methods
class ADSBClient(BaseClient):
    def __init__(self, host, port, rawtype):
        super(ModesClient, self).__init__(host, port, rawtype)

    def handle_messages(self, messages):
        for msg, ts in messages:
            if len(msg) < 28:           # wrong data length
                continue

            df = pms.df(msg)

            if df != 17:                # not ADSB
                continue

            if '1' in pms.crc(msg):     # CRC fail
                continue

            icao = pms.adsb.icao(msg)
            tc = pms.adsb.typecode(msg)

            # TODO: write you magic code here
            print ts, icao, tc, msg

client = ADSBClient(host='127.0.0.1', port=30334, rawtype=''beast')
client.run()
```

**Comment by kelvinxuande** [comment]
Thank you so much for your input. Much appreciated. I have gotten past that hurdle and learnt much.
I have an added concern: looking at the code, I realised that it is highly likely that some data messages could have been lost, since the data stream is continuous and there are multiple data handling functions, during which incoming data is not being collected and hence lost - Is this observation accurate from your point-of-view? 
If so, it seems to me that it should have utilized multiprocessing (since multithreading is 'not truly' concurrent/ parallel due to Global Interpreter Lock).
With regards to this, is there any way/ need of checking if any transmitted data was lost and are there any speed requirements placed on data handling to ensure that no data is lost?

**Comment by meneerbo** [comment]
I tried to run this as well, but at startup it gives me the following error:
name 'ModesClient' is not defined
I have pyModeS 2 installed, so maybe there is something else I need to install?

**Comment by junzis** [comment]
@meneerbo You are right.

``ModesClient`` should be ``ADSBClient``. I just updated the earlier example code.

**Comment by meneerbo** [comment]
Thanks for the prompt reply and fix.
