### ISSUE TITLE
Need Help for setup

### ISSUE THREAD

**Issue by helmiTouel** [junzis/pyModeS#41]
I found your work on ADS-B decoding and I found it very interesting. 
I installed pyModeS-2.1 on my Pi3B+. Would you help me for next steps ? 

I have a very little experience in the world of flight trucking. 
I have a DVB-T + PI3B+, I run dump1090 and I launch h=localhost:8080. 
That's basically what I know. I never used ModeSMixer neither PlanePlotter.

What should I do with pyModeS, how to launch it  ? How can I display the A/C ?
should I install PlanePlotter on my PC?

I will be very grateful if you can help me.

**Comment by junzis** [comment]
Thank you! pyModeS is aimed for low-level decoding, which is primarily used as a python package. There isn't any visualization planned yet. 

I think dump1090 is better suited for your propose. A google search on dump1090 tutorial gives me this: https://www.satsignal.eu/raspberry-pi/dump1090.html, which looks quite detailed.
