### ISSUE TITLE
Anomalous Short Message Decoding Interferance

### ISSUE THREAD

**Issue by amhirsch** [junzis/pyModeS#42]
The following messages have come from `dump1090-fa` beast feed on `localhost:30005` are clearly incorrect.
The options `--modeac` and `--no-crc-check` are **not** enabled.

>8DA993F1588D03
>8DAA703060A1E3
>8DACDDBE5839D6
>8DAA70306045F6
>8DA6B1A3583BC6

These messages are decoded as DF-17 Airborne position messages.

```python
short_msg = ['8DA993F1588D03', '8DAA703060A1E3', '8DACDDBE5839D6',\
    '8DAA70306045F6', '8DA6B1A3583BC6']

# Check the downlink format on the messages
print(list(map(pyModeS.df, short_msg)))

# Check the DF-17 typecodes
print(list(map(pyModeS.adsb.typecode, short_msg)))

# Check CRC
print(list(map(pyModeS.crc, short_msg)))
```
outputs
```python
[17, 17, 17, 17, 17]
[11, 12, 11, 12, 11]
[4234818, 3962231, 11421160, 3969378, 3049442]
```

This caused problems in my repository when the messages were sent to `pyModeS.adsb.airborne_position()` or `pyModeS.adsb.airborne_position_with_ref()`

I currently see two possible solutions:
* run `pyModeS.crc()` on each message, which is costly on a Raspberry Pi
* verify `len(msg) == 28` for the DF-17 Messages

Has anyone else had similar experiences with `dump1090`?

**Comment by junzis** [comment]
Ok, fixed now in 24806f7. I added an additional check on the downlink format in addition to the message length.
