### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by kelvinxuande** [junzis/pyModeS#46]
Just a quick note (in the open-source spirit) to anyone who may be interested; I have written an alternative client-side implementation with similar core modules that utilises multiprocessing in an attempt to multilat mode-AC messages as well. The source code can be found here: [https://github.com/kelvinxuande/dso_internship_mlat-client](url). I would really appreciate any comments on it as well!

**Comment by junzis** [comment]
@kelvinxuande - Nice work! Thanks for sharing. The multi-processing and better timestamping would be great to be included in pyModeS too.

**Comment by junzis** [comment]
Multiprocessing implemented in cfcd21b now.
