### ISSUE TITLE
quality of airbone positions

### ISSUE THREAD

**Issue by wrobell** [junzis/pyModeS#60]
Please consider the script below. Its output is as follows (columns are timestamp, typecode, oe flag and message)
```
2019-03-23 20:08:47.011677+00:00 11 1 8d4ca5415809670448d60d2fc835
2019-03-23 20:08:47.124150+00:00 19 1 8d4ca541990c9f02183c1e845693
2019-03-23 20:08:47.730598+00:00 29 0 8d4ca541ea05f9271b1c0891d457
2019-03-23 20:08:47.978328+00:00 11 0 8d4ca541580953cf23c531144f9b
message pair: (71.71367, 177.70279)
even message with ref: (53.71367, -1.18142)
odd message with ref: (53.41534, -6.16163)
```
I have received sequence of above messages. If I calculate the position using message pairs, then the position is far, far away from the airport near by I am getting the messages. When calculating the positions using reference location (Dublin airport) the result looks more plausible.

Is that normal?

The script
```
from dateutil.parser import isoparse
import pyModeS as pms

data = [
    (isoparse('2019-03-23 20:08:47.011677+00'), '8d4ca5415809670448d60d2fc835'),
    (isoparse('2019-03-23 20:08:47.124150+00'), '8d4ca541990c9f02183c1e845693'),
    (isoparse('2019-03-23 20:08:47.730598+00'), '8d4ca541ea05f9271b1c0891d457'),
    (isoparse('2019-03-23 20:08:47.978328+00'), '8d4ca541580953cf23c531144f9b'),
]

for ts, msg in data:
    print(ts, pms.adsb.typecode(msg), pms.adsb.oe_flag(msg), msg)

ts_even, msg_even = data[-1]
ts_odd, msg_odd = data[0]
pos = pms.adsb.position(msg_even, msg_odd, ts_even, ts_odd)
print('message pair:', pos)

pos = pms.adsb.position_with_ref(msg_even, 53.421389, -6.27)
print('even message with ref:', pos)

pos = pms.adsb.position_with_ref(msg_odd, 53.421389, -6.27)
print('odd message with ref:', pos)
```

**Comment by wrobell** [comment]
I also recalculated all positions in my database with the following algorithm
```
pairs = defaultdict(lambda: [(None, None), (None, None)])
for ts, icao, odd, msg in data:
    pairs[icao][odd] = (ts, msg)
    (ts1, m1), (ts2, m2) = pairs[icao]
    if ts1 is not None and ts2 is not None and abs(ts1 - ts2).total_seconds() < 180:
        yield pms.adsb.position(m1, m2, ts1, ts2)
```
and plotted it on a map

![pairs](https://gist.github.com/wrobell/7b264702a678ffdc8010778fa9fd0a8d/raw/756a573c23ce75628782b335fbb8e32517943318/2020-02-27-pos-pairs.png)

As you can see I can provide a lot of examples where there is some issue with calculation or my data or the algorithm above.

For comparison, below all the positions recalculated using reference position

![ref](https://gist.github.com/wrobell/7b264702a678ffdc8010778fa9fd0a8d/raw/756a573c23ce75628782b335fbb8e32517943318/2020-02-27-pos-ref.png)

**Comment by junzis** [comment]
I think the CPR algorithm is correctly implemented in pyModeS. However, it is possible that the decoded globally unambiguous airborne or surface position is wrong using the CPR encoding algorithm. 

According to ICAO Doc 9871, we have to perform a "reasonableness" check for these decoding results. 

This is something worth to be added to pyModeS. However, we might have to implement it in the streaming module, because the check needs additional information regarding the receive position, or aircraft positions decoded previously or later in time.

**Comment by wrobell** [comment]
Thanks for pointing me to the document. First of all, the airborne section says that the even/odd messages should be no more than 10s apart[1]. After correction of my algorithm the map looks bit better (and it yields few million less positions, which is understandable)

![pairs](https://gist.github.com/wrobell/7b264702a678ffdc8010778fa9fd0a8d/raw/a5a293b3d308a335a0614a8d5da2a790b5093987/2020-03-01-pos-pairs-10s.png)

[1] I can see you use the same value for odd/even message in streaming module as well, but when using reference position you use as much as 180s, while the document seems to suggest 25s/50s depending on the ground speed.

**Comment by wrobell** [comment]
I looked more into the document. It says that first, a pair of messages should be used to calculate position (global). Then the position should be used as reference position for next message (local) and new position becomes new reference position.

If I have not missed anything your streaming module implements above.

Using such algorithm, the map looks much better (and I get few million positions back)

![pairs](https://gist.github.com/wrobell/7b264702a678ffdc8010778fa9fd0a8d/raw/b834fb2a2a9df84a8f4f14cf6985188370c606ac/2020-03-01-pos-pairs-gl.png)

Probably what's left is the reasonableness test, which is different matter. Thanks for the pointers. Closing this issue.

**Comment by junzis** [comment]
> I looked more into the document. It says that first, a pair of messages should be used to calculate position (global). Then the position should be used as reference position for next message (local) and new position becomes new reference position.
> 
> If I have not missed anything your streaming module implements above.
> 
> Using such algorithm, the map looks much better (and I get few million positions back)
> 
> ![pairs](https://camo.githubusercontent.com/6a6946b91dcc89712efaa116f6a57895829c8b4e/68747470733a2f2f676973742e6769746875622e636f6d2f77726f62656c6c2f37623236343730326136373866666463383031303737386661396664306138642f7261772f623833346662326132613964663834613866346631346366363938353138383337306336303661632f323032302d30332d30312d706f732d70616972732d676c2e706e67)
> 
> Probably what's left is the reasonableness test, which is different matter. Thanks for the pointers. Closing this issue.

Looks good! It is also possible the input data from FMS to the transponder is wrong, for example, the straight line through Africa. Normally, if you know the position of your receiver, these kinds of errors can be easily filtered out.

**Comment by wrobell** [comment]
I have hacked some version of  reasonableness test in my scripts and got very good results. I will try to convert it into a proper function in next few days. One can follow commits in my project

https://gitlab.com/wrobell/sq1090/-/commits/master

My intention is to implement a reusable function. If I am successful, I can propose it be included in pyModeS via a pull request. Time will show. :)

**Comment by wrobell** [comment]
The algorithm is implemented, but for airborne positions only at the moment (see #63)

    https://gitlab.com/wrobell/sq1090/-/blob/master/sq1090/pos_parser.py

The map of positions looks much better (bit different type of map this time, the darker color shows more positions)
![map](https://gist.github.com/wrobell/7b264702a678ffdc8010778fa9fd0a8d/raw/635123f56aaa82ab0e955329ec65979378cfb966/2020-03-06-valid-positions.png)

**Comment by wrobell** [comment]
I have finished implementing the algorithm for both surface and airborne positions (see also my previous comment). The reasonableness tests, as described in the ICAO document, are very important in removal of anomalies. Still, I am getting some positions, which I suspect are not within range of my receiver. Therefore, when plotting maps like below, I am removing 1% of outliers (outliers in terms of distance). If you have questions about the algorithm, please contact me via my project's GitLab: https://gitlab.com/wrobell/sq1090/.

![map](https://gitlab.com/wrobell/sq1090/-/raw/f94301200b5bac324a3e5b212b79a20f5e117dd6/doc/images/receiver-range.png)
