### ISSUE TITLE
Latitude/Longitude return values too small

### ISSUE THREAD

**Issue by christiankast** [junzis/pyModeS#81]
Hello,
just a simple question:
"cprlat_even = util.bin2int(msgbin0[54:71]) / 131072.0"
is returning a value which is sometimes too small because bin2int is returning an 16 bit integer. CPR information is 17 bit and can't be returned as integer. In my opinion the return value must be a long value or is there something I do not understand?
Cheers Christian

**Comment by junzis** [comment]
The return of an integer is only in Python 2. In Python 3, this will return a float.
