### ISSUE TITLE
Heading and velocity decoding on surface messages

### ISSUE THREAD

**Issue by markaif** [junzis/pyModeS#9]
I've modified some files to add the heading and the velocity decoding on the surface with refference function. This could be done also on the surface position decoding, but I haven't done it yet. 

```
velocity = util.DecodeMovement(util.bin2int(msgbin[37:44]))
heading=0
if msgbin[44] == '1':
    heading = util.bin2int(msgbin[45:52]) / 128.0 * 360
```

On the utils file, this function needs also to be added:

```
def DecodeMovement(movement):
    """
    Decodes velocity parameter on surface movement messages
    """
    if (movement == 0):  # no movmement information available
        return None
    elif (movement == 1):  # aircraft stopped (G / S = 0 knots)
        return 0
    elif (movement == 2):  # G / S < 0.125 kt
        return 0.125
    elif (movement >= 3 and movement <= 8):
        return 0.125 + (movement - 3) * 0.1458333152116899
    elif (movement >= 9 and movement <= 12):
        return 1 + (movement - 9) * 0.25
    elif (movement >= 13 and movement <= 38):
        return 2 + (movement - 13) * 0.5
    elif (movement >= 39 and movement <= 93):
        return 15 + (movement - 39) * 1
    elif (movement >= 94 and movement <= 108):
        return 70 + (movement - 94) * 2
    elif (movement >= 109 and movement <= 123):
        return 100 + (movement - 109) * 5
    elif (movement == 124):  # max value!
        return 175
    elif (movement == 125):  # reserved for aircraft decelerating
        return None
    elif (movement == 126):  # reserved for aircraft accelerating
        return None
    elif (movement == 127):  # reserved for aircraft backing up
        return None
```

**Comment by junzis** [comment]
@markaif, thanks for the suggestion! I have implemented the surface velocity decoding now, however in a slightly different way. It is under now `adsb.surface_velocity()`, and also handled directly from `adsb.velocity()` 

Implemented in commit: https://github.com/junzis/pyModeS/commit/15f2833aee74f86e295bc03453d8b348cca65af5

**Comment by markaif** [comment]
@junzis Thanks for the implementation. However it seems to have a bug. On line 660 in ads.py the return statement seems to have an extra identation. I think it should be outside _if/elif/else_ structure and not inside _else_.
Thanks

**Comment by markaif** [comment]
@junzis Thanks for the integration. However, i think that the sourface_velocity funcion should return a none even if ther's no velocity found. The way it tis, only return somenthing when a velocity is found.
I think the funciotn would be much more usable if allways returned sthg even if its a _None_.
An easy solution could be sthg linke this:
`    # heading
    hdg_status = int(msgbin[44])
    if hdg_status == 1:
        hdg = round(util.bin2int(msgbin[45:52]) * 360.0 / 128.0, 1)
    else:
        hdg = None

    # ground movment / speed
    mov = util.bin2int(msgbin[37:44])

    if mov == 0 or mov > 124:
        spd = None
    elif mov == 1:
        spd = 0
    elif mov == 124:
        spd = 175
    else:
        movs = [2, 9, 13, 39, 94, 109, 124]
        kts = [0.125, 1, 2, 15, 70, 100, 175]
        i = next(m[0] for m in enumerate(movs) if m[1] > mov)
        step = (kts[i] - kts[i - 1]) * 1.0 / (movs[i] - movs[i - 1])
        spd = round(kts[i - 1] + (mov - movs[i - 1]) * step, 2)

    return spd, hdg, 0, 'GS'`

**Comment by junzis** [comment]
Hi @markaif, That's right. It was indeed a bug. I fixed it now in the new commit together with many other EHS updates. Thanks!
